<div id="view-content">
	<div class="alert alert-info" id="result">
		Aqui puedes ver el resultado de las pruebas
	</div>
	<h2>Organizame API</h2>
	<p>Todos los servicios reciben los parametros por medio de POST.</p>
	<div>
		<table class="table">
			<thead>
				<tr>
					<th>Url</th>
					<th>Parametros</th>
					<th>Respuesta</th>
					<th>Comentarios</th>
					<th>Prueba</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>http://organizame.apparkitekt.net/webservice/login</td>
					<td>{username:"abc", password:"xyz"}</td>
					<td>{success:(true | false), user_id:x}</td>
					<td>"success"=false => "user_id"=-1</td>
					<td>
						<form class="form-inline">
							<input type="text" class="input-small" id="login_username" placeholder="Username">
							<input type="password" class="input-small" id="login_password" placeholder="Password">
							<button type="button" class="btn" onClick="testLogin();">Probar</button>
						</form>						
					</td>
				</tr>
				<tr>
					<td>http://organizame.apparkitekt.net/webservice/user</td>
					<td>{id:"x"}</td>
					<td>{success:(true | false), firstname:"xx", middlename:"yy", lastname:"zz", username:"aa"}</td>
					<td>"success"=false => all other values are null</td>
					<td>
						<form class="form-inline">
							<input type="text" class="input-small" id="user_id" placeholder="userId">
							<button type="button" class="btn" onClick="testUser();">Probar</button>
						</form>
					</td>
				</tr>
				<tr>
					<td>http://organizame.apparkitekt.net/webservice/catalog</td>
					<td>{id:"x"}</td>
					<td>{success:(true | false), activities:ACTIVITIES_ARRAY}</td>
					<td>"success"=true AND ACTIVITIES_ARRAY = null => el usuario no ha creado tareas<br>Cada elemento de ACTIVITIES_ARRAY tiene este formato
						{id:ACTIVITY_ID, name:"xxx", description:"yyy", estimate:Y}<br>
						estimate=-1 => el usuario no ingreso un estimado
					</td>
					<td>
						<form class="form-inline">
							<input type="text" class="input-small" id="catalog_id" placeholder="userId">
							<button type="button" class="btn" onClick="testCatalog();">Probar</button>
						</form>
					</td>
				</tr>
				<tr>
					<td>http://organizame.apparkitekt.net/webservice/createtask</td>
					<td>{user_id:X, name:"activity_name", description:"activity_description", estimate:Y}</td>
					<td>{success:(true | false)}</td>
					<td></td>
					<td>
						<form class="form-inline">
							<input type="text" class="input-small" id="create_id" placeholder="userId">
							<input type="text" class="input-small" id="create_name" placeholder="name">
							<input type="text" class="input-small" id="create_description" placeholder="description">
							<input type="text" class="input-small" id="create_estimate" placeholder="estimate">
							<button type="button" class="btn" onClick="testCreateTask();">Probar</button>
						</form>
					</td>
				</tr>
				<tr>
					<td>http://organizame.apparkitekt.net/webservice/createuser</td>
					<td>{username:"xxx", firstname:"yyy", middlename:"zzz", lastname:"aaa", email:"user@domain", password:"bbb"}</td>
					<td>{success:(true | false), user_id:x}</td>
					<td></td>
					<td>
						<form class="form-inline">
							<input type="text" class="input-small" id="create_user_username" placeholder="name">
							<input type="text" class="input-small" id="create_user_firstname" placeholder="first name">
							<input type="text" class="input-small" id="create_user_middlename" placeholder="middle name">
							<input type="text" class="input-small" id="create_user_lastname" placeholder="last name">
							<input type="text" class="input-small" id="create_user_email" placeholder="user@domain">
							<input type="text" class="input-small" id="create_user_password" placeholder="password">
							<button type="button" class="btn" onClick="testCreateUser();">Probar</button>
						</form>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<?php $this->headScript()->captureStart();?>

function testLogin()
{
	$('#result')
		.empty()
		.append('sending username='+$('#login_username').val()+' password='+$('#login_password').val()+'<br>');
	$.ajax({
            type: "POST",
            url: "/webservice/login",
            data: {username:$('#login_username').val(),password:$('#login_password').val()},
            success: function(response) {
               	$('#result')					
					.append(JSON.stringify(response));
            }
        });
}

function testUser()
{
	$('#result')
		.empty()
		.append('sending id='+$('#user_id').val()+'<br>');
	$.ajax({
            type: "POST",
            url: "/webservice/user",
            data: {id:$('#user_id').val()},
            success: function(response) {
               	$('#result')					
					.append(JSON.stringify(response));
            }
        });
}

function testCatalog()
{
	$('#result')
		.empty()
		.append('sending id='+$('#catalog_id').val()+'<br>');
	$.ajax({
            type: "POST",
            url: "/webservice/catalog",
            data: {id:$('#catalog_id').val()},
            success: function(response) {
               	$('#result')					
					.append(JSON.stringify(response));
            }
        });
}

function testCreateTask()
{
	$('#result')
		.empty()
		.append('sending user_id='+$('#create_id').val()+' name='+$('#create_name').val()+' description='+$('#create_description').val()+' estimate='+$('#create_estimate').val()+'<br>');
	$.ajax({
            type: "POST",
            url: "/webservice/createtask",
            data: {
            	user_id:$('#create_id').val(),
            	name:$('#create_name').val(),
            	description:$('#create_description').val(),
            	estimate:$('#create_estimate').val()
            },
            success: function(response) {
               	$('#result')					
					.append(JSON.stringify(response));
            }
        });
}

function testCreateUser()
{
	$('#result')
		.empty()
		.append('sending username='+$('#create_user_username').val()+' firstname='+$('#create_user_firstname').val()+' middlename='+$('#create_user_middlename').val()+' lastname='+$('#create_user_lastname').val()+' email='+$('#create_user_email').val()+' password='+$('#create_user_password').val()+'<br>');
	$.ajax({
            type: "POST",
            url: "/webservice/createuser",
            data: {
            	username:$('#create_user_username').val(),
            	firstname:$('#create_user_firstname').val(),
            	middlename:$('#create_user_middlename').val(),
            	lastname:$('#create_user_lastname').val(),
            	email:$('#create_user_email').val(),
            	password:$('#create_user_password').val()

            },
            success: function(response) {
               	$('#result')					
					.append(JSON.stringify(response));
            }
        });
}
<?php $this->headScript()->captureEnd(); ?>