<div id="view-content">
	<h2>Organizame API</h2>
	<p>Todos los servicios reciben los parametros por medio de POST.</p>
	<div>
		<table class="table">
			<thead>
				<tr>
					<th>Url</th>
					<th>Parametros</th>
					<th>Respuesta</th>
					<th>Comentarios</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>http://organizame.apparkitekt.net/webservice/login</td>
					<td>{username:"abc", password:"xyz"}</td>
					<td>{success:(true | false), user_id:x}</td>
					<td>devuelve -1 en "user_id" cuando "success"=false</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>