<div class="container">
    <div id="view-content">
        <div class="row">
            <div class="span6">
                <?php 
                    echo $this->alert;            
                ?>
            </div>
        </div>
        <div class="row">
            <?php 
                echo $this->form->setAction($this->url());            
            ?>
        </div>
    </div>
</div>