<div id="view-content" class="span12">
        <?php echo $this->chart;?>
        <ul>
            <?php echo $this->act_list;?>
        </ul>
</div>
<?php $this->headScript()->captureStart();?>
$(document).ready(function(){
    chart = new Highcharts.Chart({
                    chart: {
                        renderTo: 'act_chart',
                        type: 'line'
                    },
                    title: {
                        text: name
                    },
                    xAxis: {
                        categories: <?php echo $this->categories?>
                    },
                    yAxis: {
                        title: {
                            text: 'DATOS'
                        }
                    },
                    plotOptions: {
                        line: {
                            dataLabels: {
                                enabled: true
                            },
                            enableMouseTracking: false
                        }
                    },
                    series: [{
                        name: 'LSC',
                        data: <?php echo $this->lsc?>
                    }, {
                        name: 'LS2',
                        data: <?php echo $this->ls2?>
                    }, {
                        name: 'LS1',
                        data: <?php echo $this->ls1?>
                    }, {
                        name: 'Media',
                        data: <?php echo $this->mean?>
                    }, {
                        name: 'Tiempo',
                        data: <?php echo $this->obs?>
                    }, {
                        name: 'LI1',
                        data: <?php echo $this->li1?>
                    }, {
                        name: 'LI2',
                        data: <?php echo $this->li2?>
                    }, {
                        name: 'LIC',
                        data: <?php echo $this->lic?>
                    }]
                });
}
);
<?php $this->headScript()->captureEnd(); ?>